version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticketing_postgres
    restart: always
    environment:
      POSTGRES_USER: engine_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: ticketing_engine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing_network

  redis:
    image: redis:7-alpine
    container_name: ticketing_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ticketing_network

networks:
  ticketing_network:
    driver: bridge

volumes:
  postgres_data: